# Site settings
title: ""
author: "kohill"
description: "This is a simple blog hosted on Github by Kohill. If you want to get in touch with me, just send a mail to kohillyang@126.com."
keywords: ""
biography: "I"
colophon: ""
baseurl: ""
url: "http://notes.kohill.cn"
github_username: kohillyang
simple_search: http://google.com/search
markdown: kramdown
cdn_prefix: /assets/cdn/
github_cdn_prefix: /assets
encoding: utf-8
permalink: /:year-:month-:day/:title.html
