#!/bin/sh /etc/rc.common
START=55
WAN6_NAME="wan6"
COUNT=10
DELAY=5
boot() {
        [ $DELAY -gt 0 ] && sleep $DELAY
        logger -t NAT6 "Probing IPv6 route"
        PROBE=0
        COUNT=1
        while [ $PROBE -eq 0 ]
        do
                if [ $COUNT -gt $MAX_TRIES ]
                then
                        logger -t NAT6 "Fatal error: No IPv6 route found (reached retry limit)" && exit 1
                fi
                sleep $COUNT
                COUNT=$((COUNT+1))
                PROBE=$(route -A inet6 | grep -c '::/0')
        done
        start
}
start(){
        WAN6_INTERFACE='pppoe-wan'
        WAN6_GATEWAY=$(route -A inet6 -e | grep "pppoe-wan" | awk '/::\/0/{print $2; exit}')
        LAN_ULA_PREFIX=$(uci get network.globals.ula_prefix)
        ip6tables -t nat -I POSTROUTING -s "$LAN_ULA_PREFIX" -o "$WAN6_INTERFACE" -j MASQUERADE
        route -A inet6 add 2000::/3 gw "$WAN6_GATEWAY" dev "$WAN6_INTERFACE"
        echo "$WAN6_GATEWAY" ."$WAN6_INTERFACE"
        exit 0
}
